### ISSUE TITLE
Console empty string bug

### ISSUE THREAD

**Issue by alexandruCarp** [tock/tock#3433] opened 2023-05-08 15:58 UTC
Printing to console a formatted output, with an empty string given as a parameter causes the app to yield infinitely.

I tried this code:

```
writeln!(
                Console::writer(),
                "Temperature: {}{}.{}*C\n",
                if temp_val > 0 { "" } else { "-" },
                i32::abs(temp_val) / 100,
                i32::abs(temp_val) % 100
            )
```

I expected to see this happen: a positive temperature value, with no explicit before the absolute value, printed to the console.

Instead, this happened: `Temperature: ` was printed to the console and nothing else happened.

It looks like the `WRITE command` in the [console capsule](https://github.com/tock/tock/blob/44f39d7c8cf5db0038606f08640bfae670127eef/capsules/src/console.rs) does not return an error in this case, but still no upcall is scheduled.

## Meta

Hardware platform: micro:bit v2

**Comment by alexandruradovici** [comment] 2023-05-09 07:58
I think the problem is here https://github.com/tock/tock/blob/44f39d7c8cf5db0038606f08640bfae670127eef/capsules/src/console.rs#L178. If the buffer length received by the system call is 0:
- the invocation of [`send`](https://github.com/tock/tock/blob/44f39d7c8cf5db0038606f08640bfae670127eef/capsules/src/console.rs#L132) will return 0 
- the system call returns `Ok(())` which means that the application will wait for an upcall that will never be fired

I think there are two ways to deal with this (and prevent apps from hanging):
1. modify the capsule to return en error when the buffer length is 0
2. modify the user space libraries to avoid sending a system call if the buffer length is 0

**Comment by hudson-ayers** [comment] 2023-05-10 03:10
Based on the console syscall docs, I agree that the fix is in the kernel, and we should modify send_new() to still schedule a callback when there is not a write in progress. Unfortunately it will be a bit of a pain that will require adding a deferred call to the console

**Comment by brghena** [comment] 2023-05-10 03:43
It seems to me like `writeln!(Console::writer(), "")` from an app should still not lock up. And it also shouldn't try to cancel on ongoing submission, since that's not what the user meant.

**Comment by jrvanwhy** [comment] 2023-05-10 16:42
> It seems to me like `writeln!(Console::writer(), "")` from an app should still not lock up. And it also shouldn't try to cancel on ongoing submission, since that's not what the user meant.

Calling the write command with a size of 0 is explicitly mentioned in the [docs](https://github.com/tock/tock/blob/master/doc/syscalls/00001_console.md#command-number-1) as a way for an app to cancel an ongoing write:

> A process may call this command with a write size of `0` to cancel a write transaction, if one is ongoing.

Maybe `libtock-rs` should check for a write of size 0 and skip the system calls in that case?

**Comment by alexandruradovici** [comment] 2023-05-19 16:22
@alexandruCarp can you make the changes so that this API verifies if the length is 0?

**Closed** 2023-08-01 17:02 UTC
