### ISSUE TITLE
Various Imix Issues From Sensys Demo

### ISSUE THREAD

**Issue by hudson-ayers** [tock/tock#1205] opened 2018-11-04 07:24 UTC
- [x] Kernel LED is exposed to userspace (#1227)
- [x] User LED blinks on panic instead of Kernel LED (#1227)
- [ ] Sensors hang sometimes, not sure if this is a hardware issue or not
- [x] remove take() from udp driver so that rcvd address is always correct, not just correct for first packet

**Comment by ppannuto** [comment] 2019-07-11 01:29
Given that the concrete problems have been solved, I'm going to close this issue. If there are still sensor hangs, let's explore that in a new issue hopefully with some pointers towards the root cause.

**Closed by ppannuto** 2019-07-11 01:29 UTC
